# データベーステスト用コンソール
# make -f Makefile.dbtest dbtest
dbtest:
	g++ -I./src \
	    -o db_test \
	    src/core/db/db_test.cpp \
	    src/core/db/database.cpp \
	    src/core/db/db_record.cpp \
	    src/core/db/db_report.cpp \
	    src/core/db/db_total.cpp \
	    -lsqlite3 -lsoci_core -lsoci_sqlite3
